-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0zBjYLmKP+95ACpt
zZGOxNyP0+07+uaMBmET84wm5+egCgYIKoZIzj0DAQehRANCAATzPxdaexnAYROp
TbKzL3P+UWqwMkc+hutVKeBY/sMSWaHiQaDauFZTt6a0RC835gKMBBaSB8luiVhF
OZvUNJih
-----END PRIVATE KEY-----